### ISSUE TITLE
Find through relationship no longer works in 0.1.3

### ISSUE THREAD

**Issue by sshaw** [orslumen/record-cache#35]
```
rails [3.2.19] (rails3216test)$ RecordCache::Version::STRING
=> "0.1.3"
rails [3.2.19] (rails3216test)$ r = Restaurant.first
  Restaurant Load (0.2ms)  SELECT `restaurants`.* FROM `restaurants` LIMIT 1
=> #<Restaurant id: 1, name: "fofinha food", created_at: "2014-09-21 20:07:38", updated_at: "2014-09-21 20:07:38">
rails [3.2.19] (rails3216test)$ x = r.users.find 5
ActiveRecord::RecordNotFound: Couldn't find Luser with id=5 [WHERE `users`.`restaurant_id` = 1]
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.19/lib/active_record/relation/finder_methods.rb:344:in `find_one'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.19/lib/active_record/relation/finder_methods.rb:315:in `find_with_ids'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.19/lib/active_record/relation/finder_methods.rb:107:in `find'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.19/lib/active_record/associations/collection_association.rb:95:in `find'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.19/lib/active_record/associations/collection_proxy.rb:46:in `find'
	from (irb):7
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/railties-3.2.19/lib/rails/commands/console.rb:47:in `start'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/railties-3.2.19/lib/rails/commands/console.rb:8:in `start'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/railties-3.2.19/lib/rails/commands.rb:41:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
rails [3.2.19] (rails3216test)$ r.users.find { |u| u.id == 5 }
=> #<Luser id: 5, name: "xxx", restaurant_id: 1, created_at: "2014-09-21 23:29:56", updated_at: "2014-09-21 23:29:56">
```
Here are the models:

```
~/code/ruby/rails3216test >cat app/models/{restaurant,luser}.rb
class Restaurant < ActiveRecord::Base
  cache_records :store => :shared
  attr_accessible :name
  has_many :users, :dependent => :destroy, :class_name => "Luser"
end
class Luser < ActiveRecord::Base
  set_table_name "users"
  cache_records :store => :shared, :index => [:restaurant_id]

  belongs_to :restaurant
  attr_accessible :name
  accepts_nested_attributes_for :restaurant
end
```

**Comment by sshaw** [comment]
This looks to be fixed in 0.1.6. Closing.
