### ISSUE TITLE
Active Record 4.2/Rails 4.2 Support

### ISSUE THREAD

**Issue by jdejong** [orslumen/record-cache#50]
Hi, 

Has anyone had success in adding support for AR 4.2? It looks like something fundamentally changed in AR that will require some major changes to the general code and not just adding the 4.2  datastore file. 

for example 

```
NoMethodError:
         undefined method `to_i' for #<Arel::Nodes::Casted:0x007fe2a2b5d5d8>
       # ./lib/record_cache/query.rb:88:in `block in array_of_values'
       # ./lib/record_cache/query.rb:88:in `map'
       # ./lib/record_cache/query.rb:88:in `array_of_values'
       # ./lib/record_cache/query.rb:25:in `where_values'
       # ./lib/record_cache/strategy/unique_index_cache.rb:38:in `cacheable?'
       # ./lib/record_cache/dispatcher.rb:44:in `block in fetch'
       # ./lib/record_cache/dispatcher.rb:44:in `each'
       # ./lib/record_cache/dispatcher.rb:44:in `detect'
       # ./lib/record_cache/dispatcher.rb:44:in `fetch'
       # ./lib/record_cache/datastore/active_record_42.rb:54:in `try_record_cache'
       # ./lib/record_cache/datastore/active_record_42.rb:47:in `find_by_sql_with_record_cache'
       # /Users/jdejong/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.8/lib/active_record/relation.rb:639:in `exec_queries'
       # /Users/jdejong/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.8/lib/active_record/relation.rb:515:in `load'
       # /Users/jdejong/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.8/lib/active_record/relation.rb:243:in `to_a'
       # ./spec/lib/strategy/util_spec.rb:243:in `block (3 levels) in <top (required)>'
```

There is also a bunch of general errors as well but it seems like a major rework is needed for AR 4.2. I am willing to put in some time to helping with this (already went from > 200 Tests failing to 148) but would want to know if there is any general guidance with AR 4.2 support. Thanks!

**Comment by orslumen** [comment]
I haven't looked at AR 4.2 yet, but I guess that the Adequate Record improvements have tossed things around a bit.

Unfortunately I will not be able to work on AR 4.2 support anytime soon.

The architecture of record-cache was intended to encapsulate AR version updates in the different datasource files, one for each version. Each file consists of 3 parts:
1. alias to mixin record-cache in AR at the point where the AR query is known and AR is about to retrieve the data from the DB; here data could be retrieved from the cache instead
2. code to parse the AR query and generate a "record-cache-query" record with ids, simple where filters and ordering; if the AR query structure is too complex +nil+ is returned and cache is skipped
3. cache invalidation triggers for creates/updates/deletes

It should be possible to add support for AR 4.2 by only adding a active_record_41.rb datastore file. Hope this helps you to proceed with adding AR 4.2 support, which is highly appreciated!

**Comment by danielcooper** [comment]
@jdejong Did you get anywhere with this? Would you mind posting your branch?

**Comment by jdejong** [comment]
@danielcooper I ended up switching to second_level_cache for finders and manually caching more complex requests. I would like the features of record-cache but I had an aggressive release schedule to meet so I have to skip using/fixing it for 4.2. Hopefully in the future.
